### PR TITLE
Fix for python 2.6 support on datetime.total_seconds method

### PR DESCRIPTION
**Pull request by msempere**

### CODE REVIEW

**Comment by themiurgo** [comment]
Would you mind refactoring this:
- without defining a function `total_seconds`;
- using a try / except clause (it's easier to ask for forgiveness than permission).

Also, could you squash all the commits together into one?

Thanks!

**Comment by msempere** [comment]
@themiurgo  I've performed the changes you mentioned. Let me know what do you think.
I didn't manage to squash them all in one commit.

**Comment by themiurgo** [comment]
Looks great, thanks! Could you try again to squash? You can follow this guide: http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

If you have problems with squashing I can help.

**Comment by msempere** [comment]
@themiurgo seem I dind't force the push last time and now I cannot perform it again.

**Comment by themiurgo** [comment]
I squashed this myself and merged. Thanks!

**Pull request closed without merging**
